input.onButtonPressed(Button.A, function () {
    TASA_INTERRACION = TASA_INTERRACION + 0.5
    CONTAGIOS = INFECTADOS * (TASA_INTERRACION * SUSCEPTIBLES) / (INFECTADOS + SUSCEPTIBLES) * PROBABILIDAD_CONTAGIO
    basic.showNumber(CONTAGIOS)
})
input.onButtonPressed(Button.AB, function () {
    control.reset()
})
input.onButtonPressed(Button.B, function () {
    PROBABILIDAD_CONTAGIO = PROBABILIDAD_CONTAGIO + 0.05
    CONTAGIOS = INFECTADOS * (TASA_INTERRACION * SUSCEPTIBLES) / (INFECTADOS + SUSCEPTIBLES) * PROBABILIDAD_CONTAGIO
    basic.showNumber(CONTAGIOS)
})
let CONTAGIOS = 0
let PROBABILIDAD_CONTAGIO = 0
let TASA_INTERRACION = 0
let INFECTADOS = 0
let SUSCEPTIBLES = 0
SUSCEPTIBLES = 90000
INFECTADOS = 10000
let RECUPERADOS = 0
TASA_INTERRACION = 2
PROBABILIDAD_CONTAGIO = 0.1
